pyrobopath_demo:
  ros__parameters:
    namespaces:
      - rob1
      - rob2
      - rob3

    exec_method: cartesian_planning # 'taskspace_control' or 'cartesian_planning'
    retract_height: 0.010
    collision_gap_threshold: 0.003

    rob1:
      base_frame: rob1_base_link
      eef_frame: rob1_typhoon_extruder_tcp
      task_frame: positioner

      capabilities: [0]

      eef_rotation: [0.0, 0.0, 1.0, 0.0] # w, x, y, z
      home_position: [0.0, 0.46, 0.92, 0.0, -1.38, 0.0]

      velocity: 0.050
      travel_velocity: 0.100

      collision:
        length: 0.5
        width: 0.17
        height: 0.5

        offset: [0.02, 0.0, -0.2]

      controller: rob1/joint_trajectory_controller
      joints:
        - rob1_joint_1
        - rob1_joint_2
        - rob1_joint_3
        - rob1_joint_4
        - rob1_joint_5
        - rob1_joint_6

    rob2:
      base_frame: rob2_base_link
      eef_frame: rob2_typhoon_extruder_tcp
      task_frame: positioner

      capabilities: [1]

      eef_rotation: [0.0, 0.0, 1.0, 0.0] # w, x, y, z
      # home_position: [0.0, 0.53, 0.47, 0.0, -1.0, 0.0]
      home_position: [0.0, 0.46, 0.92, 0.0, -1.38, 0.0]

      velocity: 0.050
      travel_velocity: 0.100

      collision:
        length: 0.5
        width: 0.17
        height: 0.5

        offset: [0.02, 0.0, -0.2]

      controller: rob2/joint_trajectory_controller
      joints:
        - rob2_joint_1
        - rob2_joint_2
        - rob2_joint_3
        - rob2_joint_4
        - rob2_joint_5
        - rob2_joint_6

    rob3:
      base_frame: rob3_base_link
      eef_frame: rob3_typhoon_extruder_tcp
      task_frame: positioner

      capabilities: [1]

      eef_rotation: [0.0, 0.0, 1.0, 0.0] # w, x, y, z
      # home_position: [0.0, 0.53, 0.47, 0.0, -1.0, 0.0]
      home_position: [0.0, 0.46, 0.92, 0.0, -1.38, 0.0]

      velocity: 0.050
      travel_velocity: 0.100

      collision:
        length: 0.5
        width: 0.17
        height: 0.5

        offset: [0.02, 0.0, -0.2]

      controller: rob3/joint_trajectory_controller
      joints:
        - rob3_joint_1
        - rob3_joint_2
        - rob3_joint_3
        - rob3_joint_4
        - rob3_joint_5
        - rob3_joint_6
